--- # ---
# apiVersion: 'agones.dev/v1'
# kind: GameServer
# metadata:
#   generateName: 'go-rps'
# spec:
#   ports:
#     - name: default
#       portPolicy: Dynamic
#       containerPort: 10012
#   template:
#     spec:
#       containers:
#         - name: go-rps
#           image: triberraar/go-rps:latest
#           resources:
#             requests:
#               memory: '32Mi'
#               cpu: '20m'
#             limits:
#               memory: '32Mi'
#               cpu: '20m'
apiVersion: 'agones.dev/v1'
kind: Fleet
metadata:
  name: go-rps
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 10012
      template:
        spec:
          containers:
            - name: go-rps
              image: triberraar/go-rps:latest
              resources:
                requests:
                  memory: '64Mi'
                  cpu: '20m'
                limits:
                  memory: '64Mi'
                  cpu: '20m'
---
apiVersion: 'autoscaling.agones.dev/v1'
kind: FleetAutoscaler
metadata:
  name: go-rps-autoscaler
spec:
  fleetName: go-rps
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
