apiVersion: 'agones.dev/v1'
kind: Fleet
metadata:
  name: rps
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 10012
      template:
        spec:
          containers:
            - name: rps
              image: triberraar/rps:latest
              resources:
                requests:
                  memory: '64Mi'
                  cpu: '20m'
                limits:
                  memory: '64Mi'
                  cpu: '20m'
---
apiVersion: 'autoscaling.agones.dev/v1'
kind: FleetAutoscaler
metadata:
  name: autoscaler
spec:
  fleetName: rps
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
