# Run `kubectl apply -f matchmaking.yaml` to deploy these definitions.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: triberraar-mm
  name: triberraar-mm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: geert-success
  namespace: agones-system
  labels:
    app: agones
    chart: agones-1.9.0-dev
    release: agones-manual
    heritage: Helm
subjects:
  - kind: ServiceAccount
    name: default
    namespace: triberraar-mm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-allocator
---
apiVersion: v1
kind: Pod
metadata:
  name: director
  namespace: triberraar-mm
spec:
  containers:
    - name: director
      image: triberraar/director:latest
      imagePullPolicy: Always
      resources:
        requests:
          memory: '32Mi'
          cpu: '20m'
        limits:
          memory: '32Mi'
          cpu: '20m'
  hostname: director
---
apiVersion: v1
kind: Pod
metadata:
  name: matchmaking
  namespace: triberraar-mm
  labels:
    app: battleship
    component: matchmaking
spec:
  containers:
    - name: matchmaking
      image: triberraar/matchmaking:latest
      imagePullPolicy: Always
      ports:
        - name: grpc
          containerPort: 50502
      resources:
        requests:
          memory: '32Mi'
          cpu: '20m'
        limits:
          memory: '32Mi'
          cpu: '20m'
---
kind: Service
apiVersion: v1
metadata:
  name: matchmaking
  namespace: triberraar-mm
  labels:
    app: battleship
    component: matchmaking
spec:
  selector:
    app: battleship
    component: matchmaking
  clusterIP: None
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50502
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: triberraar-mm
  labels:
    app: battleship
    component: frontend
spec:
  containers:
    - name: frontend
      image: triberraar/frontend:latest
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 10002
      resources:
        requests:
          memory: '32Mi'
          cpu: '20m'
        limits:
          memory: '32Mi'
          cpu: '20m'
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: triberraar-mm
  labels:
    app: battleship
    component: frontend
spec:
  selector:
    app: battleship
    component: frontend
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 10002
---

